[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python -m playwright install"

[deploy]
startCommand = "python main.py --bot"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 